### ISSUE TITLE
distinct metrics can have the same name

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#110]
In SCAVA for example, `newsgroups.activeusers` and `bugs.inactiveusers` have the same `name` value : `Inactive Users`
That's an issue when selecting the data for an attribute within the dropdown in ProSoul.
What I suggest to overcome this is to add the variable name next to the items in the dropdown

**Comment by mhow2** [comment]
see my comment in #247 to me, in the data dropdown, while we currently get only one entry for `Active Users` we should rather see one entry per metric available. So I wonder what metric value we get for such a metric in the current state !?

**Comment by dlumbrer** [comment]
Now the entries of the dropdown follow the nex template:

`metric_name` - `metric_id`

So we would have:

`Inactive Users` - `newsgroups.activeusers`
 
and

`Inactive Users` - `bugs.inactiveusers`
