### ISSUE TITLE
display glitch/overlap in QM's graph

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#129]
Now that we have the display for the graph, I see there are texts that overlap with each-others. And it seems the empty gap on the right is not used. Can you have a look ?

![2019-05-13_09-16](https://user-images.githubusercontent.com/9987241/57602644-01432a80-7560-11e9-939a-39e94159a586.png)

**Comment by valeriocos** [comment]
Thank you @mhow2 for reporting this issue, @dlumbrer and I will have a look at it soon.

**Comment by acs** [comment]
Hi @mhow2 !

About the empty gap, if you are referring to the box with a blue border, it is not completely working in all cases. This viewer is the one adapted from [Alambic](https://github.com/borisbaldassari/alambic)  and it needs some tweaks yet to work inside ProSoul.

**Comment by dlumbrer** [comment]
Hi @mhow2 , The PR that I submitted (#130) should fix this problem, shorting the large strings and adding a tooltip showing the complete name when hovering the node.

Thanks!
