### ISSUE TITLE
Add license headers to all files

### ISSUE THREAD

**Issue by acs** [Bitergia/prosoul#13]
The GPLv3 header is not included in python souce files in the project. They need to be added.

**Comment by vchrombie** [comment]
Hi @acs 

I would like to help with this. Can I work on this ?

**Comment by valeriocos** [comment]
sure! thank you @vchrombie . As a reference you can rely on the licenses of other components (https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/github.py#L3).

**Comment by vchrombie** [comment]
Thanks @valeriocos 

I will send a PR, to discuss any more things to add. Also on another note, the copyright information needs to be updated the perceval backend source files too.

**Comment by valeriocos** [comment]
the copyright and author info should be probably updated for all components. Maybe this task could be automated with some scripts. If you want, we can discuss it in a separated issue, WDYT?

**Comment by vchrombie** [comment]
> the copyright and author info should be probably updated for all components. Maybe this task could be automated with some scripts. If you want, we can discuss it in a separated issue, WDYT?

Okay, I am up for it. Can I open an issue regarding this in the [grimoirelab](https://github.com/chaoss/grimoirelab/) repository as it accounts for all the components?

**Comment by valeriocos** [comment]
sure!
