### ISSUE TITLE
assessing and storing time span chunks

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#131]
As discussed with Valerio I'm opening this issue.

Right now, we can assess the scores on the basis on the start/end dates selected by the user.  The resulting scores are stored back in ES as is with no relation to that time span.

What we need next is to be able to store multiple chunks back to ES, storing along the related start/end dates when the assessment took place, as well as the timestamp of the assessment itself.

As a matter of consequence, we also need to handle various case whether the data has to be overwritten when another assessment occur on the same time span.

**Comment by valeriocos** [comment]
This issue was addressed by https://github.com/Bitergia/prosoul/pull/149. Furthermore, visualizations to show QM data over quarters have been added to the QM dashboard.

@mhow2 feel free to close this issue, if you are fine with it. 

Thanks!

**Comment by mhow2** [comment]
Closing for now. Thanks !
