### ISSUE TITLE
assessment graph : scores under 1 are not displayed

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#141]
See in the following screenshot, score is zero for all metrics but it's not displayed. (it's well displayed at attribute/goal levels)

![2019-05-28_16-07](https://user-images.githubusercontent.com/9987241/58484668-cb5a9480-8162-11e9-81af-b7718d37c182.png)

**Comment by dlumbrer** [comment]
PR #147 should solve this bug

**Comment by dlumbrer** [comment]
Please @mhow2 try it when you can, feel free to reopen the issue
