### ISSUE TITLE
assessment : display calculation type

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#142]
Now that we have the possibility to choose a calculation type at the attribute level :

![2019-05-28_001](https://user-images.githubusercontent.com/9987241/58485101-ab77a080-8163-11e9-9580-612e27aaacf8.png)

From the assessment view, It could be interesting to known which calculation type has been performed for each metric.

**Comment by dlumbrer** [comment]
Hi @mhow2,

Once PR #144 is accepted, the tree and the table will show the calculation type of each metric:

![Screenshot from 2019-05-29 12-32-32](https://user-images.githubusercontent.com/9249232/58550399-eb935d80-820d-11e9-9156-59945816333e.png)
![Screenshot from 2019-05-29 12-32-19](https://user-images.githubusercontent.com/9249232/58550400-eb935d80-820d-11e9-94bc-2f318d9a8e66.png)




And the csv save the value as well:

![Screenshot from 2019-05-29 12-32-48](https://user-images.githubusercontent.com/9249232/58550412-f3530200-820d-11e9-902d-aa5095e43361.png)


Thanks

**Comment by dlumbrer** [comment]
Please @mhow2, try it when you can and feel free to reopen the issue
