### ISSUE TITLE
managing "emotion" metrics

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#143]
In SCAVA we have the Emotion analysis metrics, that provide the % distribution over five emotions from the analyzed comments, into the time spam.

For example, below are the last samples (at 20190331) from an analysis that ran between 20180101 to 20190331. It is for metric name `Comment Emotion Percentages (Cumulative)`

```json
    {
      "Date": "20190331",
      "Emotion": "__label__sadness",
      "Comments": 24.83221435546875
    },
    {
      "Date": "20190331",
      "Emotion": "__label__joy",
      "Comments": 7.382550239562988
    },
    {
      "Date": "20190331",
      "Emotion": "__label__love",
      "Comments": 12.080536842346191
    },
    {
      "Date": "20190331",
      "Emotion": "__label__surprise",
      "Comments": 4.026845455169678
    },
    {
      "Date": "20190331",
      "Emotion": "__label__anger",
      "Comments": 16.10738182067871
    }
```

So the distribution might change everyday, along with new comments coming in. (it is how I understand the "cumulative").

So to me it looks like that the value we need to assess in prosoul is the **latest sample (date)** for each emotion. For instance, here, I think we want to assess anger to `16.10` (latest sample of the analysis time span) and not any of the avg, median, max or min calculation type.

WDYT ?

**Comment by valeriocos** [comment]
@mhow2 sorry for the late reply. This feature has been added with https://github.com/Bitergia/prosoul/pull/145
If you are fine with the new feature, feel free to close this issue.

Thanks!

**Comment by mhow2** [comment]
Thanks !
