### ISSUE TITLE
invalid threshold field value leads to "Errors: Problem creating the assessment list index out of range"

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#151]
It was not obvious to me that when assessing, the message "Errors: Problem creating the assessment list index out of range" could mean that some thresholds are missing in the metric definition. Is it something that can be improved ?

We could either make threshold field mandatory - but it doesn't handy to me when you design a model without knowing much about the metric values, OR, just abort the assessment and tell "hey, assessment can't be achieved without this or that data".

**Comment by dlumbrer** [comment]
Hi @mhow2 ,

The issue is due to the fact that the thresholds value is empty or contains less than 5 values. If you agree, we can add default range values (0, 1, 10, 100, 1000 for instance).

WDYT?

**Comment by mhow2** [comment]
It wont prevent the user to type less than 5 values and then fall into the same issue. Maybe we should force the user to type at least 5 comma-separated values. WDYT ?

**Comment by dlumbrer** [comment]
I was thinking of the importing mode, there we can add the default values if there are not in the JSON.

But yes, you are right, we should force the user to type at least the thresholds in the right way.

Thanks

**Comment by mhow2** [comment]
> I was thinking of the importing mode, there we can add the default values if there are not in the JSON.

The import mode is expected to take a file that was previously exported by Prosoul, so it should be valid at export time, wdyt ?
Of course if someone tweak the JSON by hand, it is somehow "unsupported" or "at your risk" so...

**Comment by dlumbrer** [comment]
> > I was thinking of the importing mode, there we can add the default values if there are not in the JSON.
> 
> The import mode is expected to take a file that was previously exported by Prosoul, so it should be valid at export time, wdyt ?
> Of course if someone tweak the JSON by hand, it is somehow "unsupported" or "at your risk" so...

Ok, I'm going to force the user to put the right thresholds then

**Comment by dlumbrer** [comment]
@mhow2 , please test it when you can and reopen the issue if needed, thanks!
