### ISSUE TITLE
make metric "name" field mandatory

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#152]
We need this field to be mandatory, otherwise it would lead to an "empty" element in the UI, and probably an error later on when assessing.

![2019-06-06_10-44](https://user-images.githubusercontent.com/9987241/59019429-549b5680-8848-11e9-99ee-147ea9722d1d.png)

What I suggest to overcome this is to put a name based on the metric data name when creating the metric definition (and of course, not let the user create a metric without a name - should be mandatory)

![2019-06-06_10-48](https://user-images.githubusercontent.com/9987241/59019580-9d530f80-8848-11e9-8d5a-9be3aa6c9e40.png)

**Comment by mhow2** [comment]
BTW, once you have created a metric without a name, it's not possible to delete it:
![2019-06-06_10-56](https://user-images.githubusercontent.com/9987241/59020243-e0fa4900-8849-11e9-8e69-801b3eae85b9.png)

**Comment by dlumbrer** [comment]
> We need this field to be mandatory, otherwise it would lead to an "empty" element in the UI, and probably an error later on when assessing.
> 
> ![2019-06-06_10-44](https://user-images.githubusercontent.com/9987241/59019429-549b5680-8848-11e9-99ee-147ea9722d1d.png)
> 
> What I suggest to overcome this is to put a name based on the metric data name when creating the metric definition (and of course, not let the user create a metric without a name - should be mandatory)
> 
> ![2019-06-06_10-48](https://user-images.githubusercontent.com/9987241/59019580-9d530f80-8848-11e9-8d5a-9be3aa6c9e40.png)

I'll put that field as "required", thanks!

**Comment by dlumbrer** [comment]
> BTW, once you have created a metric without a name, it's not possible to delete it:
> ![2019-06-06_10-56](https://user-images.githubusercontent.com/9987241/59020243-e0fa4900-8849-11e9-8e69-801b3eae85b9.png)

If you click on "Edit" you will see the Remove button, when you are adding a new metric there is no Remove button because it does not exist yet:

![Screenshot from 2019-06-07 14-14-57](https://user-images.githubusercontent.com/9249232/59103295-c221b280-892e-11e9-945e-d3393497de3f.png)

**Comment by mhow2** [comment]
> If you click on "Edit" you will see the Remove button

That's what I did in the screenshot actually ;)

**Comment by dlumbrer** [comment]
> > If you click on "Edit" you will see the Remove button
> 
> That's what I did in the screenshot actually ;)

I see!! Sorry! It seems that is a bug when the name is blank, it must be fixed then! Sorry again @mhow2

**Comment by mhow2** [comment]
Just in case, we have reopened that one because we want to keep the form on-screen in case of a mandatory or wrong value specified, upon submit. In doing so we avoid the user to retype again all the data.

**Comment by dlumbrer** [comment]
Reviewing the way that this is done, it is not possible to maintain the data in the form because the check of the data is done on the server-side, so when this check is done it forces an HTTP response, losing the data.

If this is a high priority task we can think about how to do it. Let me know if this is the case
