### ISSUE TITLE
switching from 'view' to 'edit' view is slow

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#154]
by slow I mean, 2-3 minutes.

I know that all metric's Data names should be retrieved, but are we sure that it does only this ?

**Comment by mhow2** [comment]
looks fixed !? :joy:

**Comment by valeriocos** [comment]
Yes, it should be fixed with: https://github.com/Bitergia/prosoul/pull/160

Thank @mhow2 for the pointer
