### ISSUE TITLE
a shipped model fail to import (polarsys)

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#157]
I'm not able to import the file at https://raw.githubusercontent.com/Bitergia/prosoul/master/django-prosoul/prosoul/data/polarsys_qm.json in ProSoul. No errors is displayed either in the UI or logs but the graph is empty as well as in the edit view, when you select it has no properties.

**Comment by dlumbrer** [comment]
Hi @mhow2,

This error is due to the fact that there are some old quality models that were used to test. This QM does not have required fields that are now mandatory.

We are going to discuss if we maintain or remove them. But for now, they are not usable.

Thanks
