### ISSUE TITLE
UI: after importing a model, "view" to this model

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#165]
When you import a json file from the edit view, there is a redirection to the viewer with the first model item selected. I assume that the redirection to "view" is here to provide the user a first visual look to the freshly imported model (right ?). If we want to keep this behavior, we need the redirection to happen to the model that has just been imported.

**Comment by dlumbrer** [comment]
PR #178 has been submitted. This issue is going to be closed when merged.

THanks!
