### ISSUE TITLE
assessment graph shows data for all projects instead of selected one

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#166]
I'm providing our WIP model :  [qmodel_OW2-MRL_CMR-v0.1.9.json.txt](https://github.com/Bitergia/prosoul/files/3272367/qmodel_OW2-MRL_CMR-v0.1.9.json.txt)

If you assess against this model and select a project in the top dropdown (here `spoon`) you'll see something like follow.

![Screenshot_2019-06-10 Prosoul Quality Models Assessment](https://user-images.githubusercontent.com/9987241/59201317-7410e700-8b9a-11e9-8620-df66df47df90.png)

I would expect to see only data about `spoon`.
In addition, rounding the actual metric value could be a great addition to open up some space to this page. (two or three digits after comma could be enough).

**Comment by dlumbrer** [comment]
> In fact it could be the same as #174

We are going to follow #175!, thanks!
