### ISSUE TITLE
reverse thresholds might not work properly

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#171]
I've been testing the **Reverse Thresholds** feature in the metric property.
The thresholds are `0,20,75,100,150` and whatever I specific (yes/no) in the Reverse Thresholds, I still get a score value of `2` (the assessed value is `53`). Shouldn't I get `3` ?

**Comment by dlumbrer** [comment]
Hi @mhow2,

We have included a PR (#172) that should fix the issue. Please, test it when you can and feel free to reopen the issue if there is any problem.

Thanks!
