### ISSUE TITLE
ability to assess a same score value for several thresholds

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#173]
Let's take the metric `Method Hiding Factor (Java)`. As far as I've been told, this metric should be contained as close as possible close to 10% but not below.

For instance, if we define the thresholds `10,20,30,40,50`, it works well if we get contained in the range 10-infinite, for example a score of 4 between 10 and 20 and 0 above 50.
But in this use case we also need a score of 0 between values 0 and 10.

In the current implementation I don't think we can handle this case.

**Comment by valeriocos** [comment]
Sorry for the late reply!

If I understand correctly, you would like to focus the scores only on a specific range. For instance, you would like something similar to:
0 - 10 ---> 0
10 - 20  ---> 4
20 - 30  ---> 3
30 - 40  ---> 2
40 - 50  ---> 1
> 50  ---> 0

is that correct @mhow2 ?

**Comment by mhow2** [comment]
Well, indeed it looks a simpler way to say it. You could update the issue title if you need :)

**Comment by valeriocos** [comment]
To keep consistency in Prosoul, I would prefer to manipulate the metric during the scava2es process (removing the values from 0 to 10). I will open a PR in scava and mention this issue.

**Comment by valeriocos** [comment]
PR ready on scava: https://github.com/crossminer/scava/pull/333

**Comment by mhow2** [comment]
I'm closing that one. Thanks.
