### ISSUE TITLE
Assessement project selection w/graph weird thing

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#174]
In the screenshot below, I have selected 'spoon'. I don't understand why I rather see `cliflegacy` there.
Here is the model used :
[qmodel_OW2-MRL_CMR-v0.2.4.json.txt](https://github.com/Bitergia/prosoul/files/3622075/qmodel_OW2-MRL_CMR-v0.2.4.json.txt)

![image](https://user-images.githubusercontent.com/9987241/64774589-c6282680-d554-11e9-8abe-c7f834300382.png)

**Comment by mhow2** [comment]
Here is another screenshot I have as an example:
![image](https://user-images.githubusercontent.com/9987241/65053958-134d3380-d96d-11e9-8a19-541d260189e2.png)

**Comment by dlumbrer** [comment]
It reminds me of an old issue of Prosoul, I have been testing the issue with the last version and I don't see this problem. Could you try again with the last Prosoul image?

Please, reopen the issue if the problem keeps

**Comment by mhow2** [comment]
Hi @dlumbrer , thank you. But I reproduced just a few days ago and I still can. You can test by yourself with http://scava-dev.ow2.org:8000/prosoul/create_assessment
There you can assess between 2018 and 2020 and check
PS: I still cannot reopen issues in the project

**Comment by dlumbrer** [comment]
> Hi @dlumbrer , thank you. But I reproduced just a few days ago and I still can. You can test by yourself with http://scava-dev.ow2.org:8000/prosoul/create_assessment
> There you can assess between 2018 and 2020 and check
> PS: I still cannot reopen issues in the project

Thanks for sharing the url to test it!, you were right. This PR #179 should fix it
