### ISSUE TITLE
missing attributes in goals

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#176]
In the assessment table, in each goals I see some attributes are missing.
See the original model : 
[qmodel_OW2-MRL_CMR-v0.2.4.json.txt](https://github.com/Bitergia/prosoul/files/3622087/qmodel_OW2-MRL_CMR-v0.2.4.json.txt)

for this specific screenshot extract , the goal `MRL_Sustainability` misses the attribute `Sustainability_CMR`

![image](https://user-images.githubusercontent.com/9987241/65054636-2f9da000-d96e-11e9-9dd5-02268995e50a.png)

**Comment by dlumbrer** [comment]
This behavior appears due to the project does not have assessment in that attribute.

Please, feel free to reopen the issue

**Comment by mhow2** [comment]
"no assessment" you mean no value ? I would have a line for the attribute, telling there is no value at all for the metrics. WDYT ? The goal is to have a clear overview of which Attributes miss all the values.

**Comment by dlumbrer** [comment]
> "no assessment" you mean no value ? I would have a line for the attribute, telling there is no value at all for the metrics. WDYT ? The goal is to have a clear overview of which Attributes miss all the values.

Yes, I mean no value, sorry. The data structure of the assessment does not retrieve the attribute if does not have an assessment value, so this change may be tough
