### ISSUE TITLE
data empty with new "data" field dropdown

### ISSUE THREAD

**Issue by mhow2** [Bitergia/prosoul#184]
Since we have made #110 or maybe #111, there is an issue when you select the metric data in the dropdown with the scheme <metricname> - <metricId>. For instance with `Unanswered Bugs - bugs.unansweredBugs` => the system cannot find any value for the metric. However if you choose  `Unanswered Bugs` it starts working.

![image](https://user-images.githubusercontent.com/9987241/65677081-466c8280-e051-11e9-898b-7865c4c66856.png)

Can you check @dlumbrer ?

**Comment by mhow2** [comment]
In the json it is stored as `"data_implementation": "OMM_DOC - omm_OMM_DOC"` , so it might be that the system use this value to search ES, which would probably fail.

**Comment by dlumbrer** [comment]
> In the json it is stored as `"data_implementation": "OMM_DOC - omm_OMM_DOC"` , so it might be that the system use this value to search ES, which would probably fail.

That's probably the issue, I will fix it ASAP, thanks for the reporting @mhow2

**Comment by mhow2** [comment]
Thanks @dlumbrer , keep me informed

**Comment by dlumbrer** [comment]
Hi @mhow2 ,

A PR (#185) has been submitted, as you said the problem is that we were doing the assessment with the wrong metric_data name.

Once included, this issue must be solved

Thanks

**Comment by mhow2** [comment]
Would it means that I'll have to re-apply all the metric form one by one ?
I'll wait for the fix to be merged in order to test (I'm using the Docker image).

**Comment by dlumbrer** [comment]
> Would it means that I'll have to re-apply all the metric form one by one ?
> I'll wait for the fix to be merged in order to test (I'm using the Docker image).

No, it is just a simple change, It will use the right name to assess but you will see in the selection form the `name - id`. So you wouldn't have to change anything
