### ISSUE TITLE
index_pattern is not up to date in the templates

### ISSUE THREAD

**Issue by vchrombie** [Bitergia/prosoul#204]
I was facing problems when I tried to visualize the QM using Prosoul.

![1](https://user-images.githubusercontent.com/25265451/77745047-9ba94100-7040-11ea-9de3-970c9c758e24.png)

But the result of the dashboard was empty.

![2](https://user-images.githubusercontent.com/25265451/77745060-a19f2200-7040-11ea-9d18-dc2f0d546f11.png)

The whole procedure can be found at https://github.com/vchrombie/chaoss-microtasks/issues/11#issuecomment-604919542. 

With the help of @valeriocos, I realized that the dashboards are not updated automatically. The index_pattern isn't up to date in the [attribute-template.json](https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/panels/templates/attribute-template.json).

**Comment by vchrombie** [comment]
One possible solution is to update the dashboard in the local instance manually and export the dashboard using [kidash](https://github.com/chaoss/grimoirelab-kidash) and update the existing index_pattern.

@valeriocos, correct me if I am wrong.

I am working on this and I will be sending a patch to this soon.
Thanks. :slightly_smiling_face:

**Comment by valeriocos** [comment]
Thanks @vchrombie for reporting this error!

> I am working on this and I will be sending a patch to this soon.

Great!
