### ISSUE TITLE
Kibana dashboard URL doesn't have the port number

### ISSUE THREAD

**Issue by vchrombie** [Bitergia/prosoul#205]
Whenever we generate a dashboard (either in Visualize or Assessment), we get the link of the dashboard as localhost/app/kibana#/dashboards, but that doesn't seem to work as kibiter is at the port 5601. The correct link is localhost:5601/app/kibana#/dashboards

![](https://raw.githubusercontent.com/vchrombie/chaoss-microtasks/master/microtask-9/images/qm_visualize_result.png)

We mention the Kibana URL along with the port number but it doesn't carry in the result. I checked the code.

visualization_config.html
```
{% if kibana_url %}
<div class="row">
  <div class="col-sm-12">
    Your <a href="{{ kibana_url }}/app/kibana#/dashboards">Quality Model dashboard</a>. Enjoy it!
  </div>
</div>
{% endif %}
```
It seems that kibana_url doesn't carry the port number. 

@valeriocos @dlumbrer, any workaround for this problem?

**Comment by dlumbrer** [comment]
Hi @vchrombie ,

The `kibana_url` URL is defined by the env variable `KIBITER_HOST`, specifically here:

https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L40

If the env variable doesn't exist it uses `http://localhost:80` by default. So, if you define the variable in your env linking your kibana it should work.


Let us know if works! thanks!

**Comment by vchrombie** [comment]
Thanks @dlumbrer for the reply.

> The `kibana_url` URL is defined by the env variable `KIBITER_HOST`, specifically here:
> 
> https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L40

Thanks for the clarification. 

> If the env variable doesn't exist it uses `http://localhost:80` by default. So, if you define the variable in your env linking your kibana it should work.

Sure, I would try this and let you know how it goes.

**Comment by vchrombie** [comment]
Hi @dlumbrer, I have another small doubt.

> The `kibana_url` URL is defined by the env variable `KIBITER_HOST`, specifically here:
> 
> https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L40

I had a look at the codebase and understood the logic. I see that we are updating the `kibana_url` with the `KIBANA_HOST` for the visualization and assessment.

https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L108

We need to input the `kibana_url` in the visualization form, is any reason not using the same instead of `KIBANA_HOST`.  

https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/templates/prosoul/visualization_config.html#L22

I understand one point that during the assessment, we will miss the `kibana_url`. 

Let me know if it is not clear or if there is something I missed.

> If the env variable doesn't exist it uses `http://localhost:80` by default. So, if you define the variable in your env linking your kibana it should work.

I think we can note this for future reference. If we are planning to add a Troubleshooting section, we can add this to that.

**Comment by dlumbrer** [comment]
> Hi @dlumbrer, I have another small doubt.
> 
> > The `kibana_url` URL is defined by the env variable `KIBITER_HOST`, specifically here:
> > https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L40
> 
> I had a look at the codebase and understood the logic. I see that we are updating the `kibana_url` with the `KIBANA_HOST` for the visualization and assessment.
> 
> https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L108
> 
> We need to input the `kibana_url` in the visualization form, is any reason not using the same instead of `KIBANA_HOST`.
> 
> https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/templates/prosoul/visualization_config.html#L22
> 
> I understand one point that during the assessment, we will miss the `kibana_url`.

I think I don't understand the question here. We took the `kibana_url` from the form as well:

https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L91



> 
> Let me know if it is not clear or if there is something I missed.
> Thanks.
> 
> > If the env variable doesn't exist it uses `http://localhost:80` by default. So, if you define the variable in your env linking your kibana it should work.
> 
> I think we can note this for future reference. If we are planning to add a Troubleshooting section, we can add this to that.

Yes, that's a good idea

**Comment by vchrombie** [comment]
> > I had a look at the codebase and understood the logic. I see that we are updating the `kibana_url` with the `KIBANA_HOST` for the visualization and assessment.
> > https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L108

> I think I don't understand the question here. We took the `kibana_url` from the form as well:
> 
> https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L91

Sorry for not being clear. I understood the `kibana_url` was taken from the form. I was asking if it is possible to return the same `kibana_url` instead of `KIBANA_HOST`.

I just want to see if it is possible without configuring the variable in the environment.

**Comment by dlumbrer** [comment]
> > > I had a look at the codebase and understood the logic. I see that we are updating the `kibana_url` with the `KIBANA_HOST` for the visualization and assessment.
> > > https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L108
> 
> > I think I don't understand the question here. We took the `kibana_url` from the form as well:
> > https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L91
> 
> Sorry for not being clear. I understood the `kibana_url` was taken from the form. I was asking if it is possible to return the same `kibana_url` instead of `KIBANA_HOST`.
> 
> I just want to see if it is possible without configuring the variable in the environment.

Oh I see!, sorry, I missundertood the question. Yes, I think we should change:

**Comment by dlumbrer** [comment]
> Thanks for the quick reply, @dlumbrer.
> 
> > Oh, I see!, sorry, I misunderstood the question. Yes, I think we should change:
> > https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L91
> > returning directly the `kibana_url` variable (the one taken from the form).
> 
> Okay! 
> 
> Also, I think we should not be removing `KIBANA_HOST` completely as well because the assessment would break in that case.
> https://github.com/Bitergia/prosoul/blob/master/django-prosoul/prosoul/views.py#L192

You are right, maybe we can develop the next behavior:

- If the form is not filled with the URL of Kibana, we use the `KIBANA_HOST` env. But it filled, we use just the `kibana_url` param of the form.

**Comment by vchrombie** [comment]
Hi @dlumbrer 

> You are right, maybe we can develop the next behavior:
> 
> * If the form is not filled with the URL of Kibana, we use the `KIBANA_HOST` env. But it filled, we use just the `kibana_url` param of the form.

I guess the `kibana_url` param is already mandatory I guess. Never mind, but it is good to implement it in that way. :slightly_smiling_face:

**Comment by vchrombie** [comment]
Hi @dlumbrer 
Thanks for the help and clearing out the problem.
I want to ask if you have fixed it or planning to fix it.

Is it ok if I send a PR to fix this issue?

**Comment by dlumbrer** [comment]
> Hi @dlumbrer
> Thanks for the help and clearing out the problem.
> I want to ask if you have fixed it or planning to fix it
> Is it ok if I send a PR to fix this issue?

Sure! Of course you can do it! It would be awesome 👍😄

**Comment by vchrombie** [comment]
I have sent the PR. :smile: 

> if you define the variable in your env linking your kibana it should work.

Thank you @dlumbrer for the help. I could fix it. I would like to share the procedure here.

I was not using docker for prosoul. I was using the source code to build Prosoul. So, I did the following procedure.
1. Deactivate the virtual environment you are using currently.
2. add the activate script of the virtual environment
```
sudo nano virtual_env/bin/activate
```
3. add the line `export KIBITER_HOST="http://localhost:5601"` to the end of the file.
4. restart the environment.

That's it. It worked like charm. Both the result links (Viz and Assess) work fine now.

**Comment by dlumbrer** [comment]
I tried the PR and it works as expected. Great job :+1:!

Thanks @vchrombie
