### ISSUE TITLE
[Travis] upgrade pip and setuptools

### ISSUE THREAD

**Issue by valeriocos** [Bitergia/prosoul#208]
Following https://github.com/chaoss/grimoirelab-perceval/pull/643, the same fix should be applied to Prosoul. 

@vchrombie do you want to prepare the PR? Thanks

**Comment by vchrombie** [comment]
Sure @valeriocos, I would be happy to help you with it. :smile:

**Comment by valeriocos** [comment]
Thank you @vchrombie !
