### ISSUE TITLE
Add REST API methods for doing the visualization and assessment

### ISSUE THREAD

**Issue by acs** [Bitergia/prosoul#81]
The current REST API implements the full CRUD operations for all the data model used in ProSoul. But it lacks the operations for building a visualization for a quality model, or doing its assessment. 

These operations must be added to the REST API also.

**Comment by valeriocos** [comment]
This issue should have been fixed with: https://github.com/Bitergia/prosoul/pull/118

@dlumbrer can we close it ?

**Comment by dlumbrer** [comment]
Sure!
